# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b41d9d9dae278c67adf63ecbad1f61a205a19ba577e08d2f3229e6acbaca7f90cc597bbf39f6c12beeaa3787316a1bbe46c1e3881986b7b76289e78b598dc403

test:
  secret_key_base: cd6911c4c9071c259239cddc8353905d9e36584235a35768bcbb4550966d704d1c1eb6c04a43963849b35a3302f590cb75a6c3c4b49cffd7456ba60a9e7653f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
